- src/components/common/Button.jsx
> feat:공통 버튼 컴포넌트 구현

- src/components/common/Button.jsx
> fix: 공통 버튼 수정

- package-lock.json
- package.json
- src/app/page.js
- src/components/ui/input/CounterInput.jsx
- src/components/ui/input/DropdownInput.jsx
- src/components/ui/input/Input.jsx
- src/components/ui/input/SearchInput.jsx
- src/components/ui/input/TextboxInput.jsx
- src/components/ui/input/TokenInput.jsx
- src/components/ui/input/UploadInput.jsx
- src/components/ui/input/index.js
* Input 관련 7가지 컴포넌트 구현 완료
1. 기본 입력(Input.jsx): 텍스트, 비밀번호, 텍스트영역 지원
2. 검색 입력(SearchInput.jsx): 검색 아이콘 및 검색 이벤트 처리
3. 드롭다운(DropdownInput.jsx): 선택 옵션 목록 제공
4. 여러 줄 입력(TextboxInput.jsx): 긴 텍스트 입력에 최적화
5. 토큰/포인트 입력(TokenInput.jsx): 숫자 입력 및 단위 표시
6. 수량 조절(CounterInput.jsx): +/- 버튼으로 수량 조절
7. 파일 업로드(UploadInput.jsx): 파일 선택 및 업로드 지원
- 공통 스타일 및 반응형 디자인 적용
- Input 컴포넌트 사용 가이드 문서 작성
> [기능] Input 컴포넌트 구현

- src/components/common/Button.jsx
> button-component-수정

- src/app/page.js
- CounterInput 컴포넌트에 showMaxInfo prop 추가
- 최대값 정보(/ {max}, 최대 {maxText}) 표시/숨김 제어 가능
- 기본값 true로 설정하여 기존 동작 유지
- 사용 사례에 따라 유연한 UI 제공
> [기능] CounterInput 컴포넌트 최대값 정보 표시 제어 옵션 추가

- src/app/auth/login/page.jsx
- src/app/auth/signup/page.jsx
- src/components/layout/Header.jsx
- src/components/ui/input/Input.jsx
- 일반 텍스트 입력(type="text")에 30자 제한 자동 적용
- "{라벨명}은 최대 30자까지 입력 가능합니다." 에러 메시지 표시
- 별도의 prop 추가 없이 type="text"인 경우에만 자동 적용
- 기존 error prop과 충돌하지 않도록 처리
> [기능] Input 컴포넌트 텍스트 필드 30자 제한 추가

- src/components/common/Modal.jsx
- src/components/layout/NoHeader.jsx
- src/components/ui/card/cardProfile/BuyerCardItem.jsx
- src/context/ModalContext.jsx
- 노헤더 컴포넌트 링크 컴포넌트 /market으로 수정
- 모달 컴포넌트 모달프로바이더와 연결
- buyer 컴포넌트에서 "포토카드 구매하기" 버튼을 누르면 모달이 등장하도록 연결
> feat: 버튼과 모달 연결

- src/app/not-found.jsx
- src/app/purchase/[id]/page.jsx
- src/components/common/CardModal.jsx
- src/components/ui/card/cardProfile/BuyerCardItem.jsx
- src/lib/api/purchase.js
- 카드 생성, 구매 교환 등 전역적으로 사용되는 카드 모달 제작
- 이후 API 연동 
-
> feat: 카드모달 제작

- package-lock.json
- public/icons/ic_m_close.svg
- src/components/layout/Header.jsx
- src/components/layout/NotificationModal.jsx
> feat: 알림 UI 구현

- src/app/page.jsx
- 버튼 컴포넌트로 변경
- 서버 컴포넌트로 만들기 위해 link이용
> fix: 버튼 컴포넌트 사용

- src/app/purchase/[id]/page.jsx
- src/components/modal/ModalRenderer.jsx
- src/components/modal/layout/CardModal.jsx
- src/components/ui/card/cardProfile/BuyerCardItem.jsx
- src/lib/api/purchase.js
> Feat: 구매 API 연동 및 카드 모달 연결 

- src/app/my-gallary/page.jsx
- src/components/ui/input/DropdownInput.jsx
- 마이갤러리 등급 필터 및 생성 버튼 UI 개선 (월/횟수 표시 포함)
- 드롭다운 인풋 잘리는 문제 개선
> style: 마이갤러리 UI 디자인 수정 및 레이아웃 개선

- src/app/my-gallery/create/page.jsx
- src/app/my-gallery/page.jsx
- src/app/page.jsx
- src/components/modal/layout/DesktopModal.jsx
- src/components/ui/input/DropdownInput.jsx
- src/lib/api/galleryApi.js
- fix: 랜딩페이지 링크 경로를 `/market`으로 수정하여 라우팅 오류 해결
- style: 드롭다운 인풋 너비를 반응형에 맞게 조정
- refactor: `DesktopModal`에서 `useModal` 제거, `onClose` props 기반 제어로 변경
- feat: 마이갤러리 생성 페이지 추가 (`/my-gallery/create` 등)
> 마이갤러리 페이지 기능 개선 및 생성 페이지 추가

- public/icons/ic_back.svg
- src/app/market/page.jsx
- src/app/my-gallery/create/page.jsx
- src/app/my-gallery/page.jsx
- src/components/modal/layout/FullScreenModal.jsx
- src/components/ui/card/cardOverview/CardImage.jsx
- src/components/ui/input/DropdownInput.jsx
- src/components/ui/input/UploadInput.jsx
- src/lib/api/galleryApi.js
- src/lib/api/marketApi.js
- 포토카드 생성 페이지 구현
- 이미지 업로드 처리 및 미리보기 기능 추가
- 전체화면 모달(FullScreenModal) 레이아웃 컴포넌트 구현
- 업로드한 이미지가 카드에 표시되지 않던 문제 해결
- 드롭다운 인풋의 너비 잘림 및 z-index 겹침 이슈 수정
- 업로드 인풋에서 이미지 반영되지 않던 문제 해결
> 포토카드 생성 기능 및 UI 개선사항 반영

- src/app/sale/[id]/page.jsx
- src/components/common/CardDetailSection.jsx
- src/components/exchange/ExchangeSuggest.jsx
- src/components/ui/card/cardOverview/CardOverview.jsx
> feat:거래 제안 컴포넌트 제작

- src/app/purchase/[id]/page.jsx
- src/lib/api/purchase.js
- 410 에러 발생 시 데이터를 백에서 안보내는 문제 백과 같이 해결
- 구매 판매 공통 스타일 컴포넌트로 변경
> fix: 410에러 코드 발생 시 데이터를 안보이게 하는 문제 해결

- src/app/market/page.jsx
- src/app/my-gallery/page.jsx
- src/app/sale/page.jsx
- src/components/layout/ProfileMobileModal.jsx
- src/components/market/FilterBottomSheet.jsx
- src/components/ui/skeleton/CardOverviewSkeleton.jsx
- src/utils/countFilterValues.js
- 마켓플레이스 :  페이지 리팩토링
- 마이갤러리 페이지 : useQuery 기반 카드 조회 로직 통합 및 정리
- 판매 페이지 : 필터 조건 생성 로직 개선, 판매방법 필터 기능 추가 
- TODO: 카드 타입 수정 예정(for_sale > saleState만 다르게)
- 판매방법 필터 바텀시트/드롭다운 로직 통일
- 프로필 모달 네이밍 및 import 경로 정리
- 스켈레톤 UI 스타일 개선 (border opacity 추가)
> 마켓/마이갤러리/판매 페이지 리팩토링 및 판매방법 필터 수정

- package-lock.json
- package.json
- src/app/globals.css
- src/app/market/page.jsx
- src/app/my-gallery/create/page.jsx
- src/app/my-gallery/page.jsx
- src/app/sale/page.jsx
- src/components/market/MyCardsSellBottomSheet.jsx
- src/lib/api/galleryApi.js
- src/lib/api/shop.js
- react-hook-form 패키지 설치
- 페이지 리팩토링 및 코드 정리
- 카드 불러오기 실패 이슈 해결
- axios → fetch로 API 호출 방식 변경
- 커스텀 스크롤바 스타일 적용
- 코드 전반 리팩토링을 통해 가독성 개선
- axios 제거로 의존성 간소화
- UI 사용자 경험 개선을 위한 스크롤바 스타일링 추가
> 리팩토링 및 카드 조회 기능 안정화

- src/app/market/page.jsx
- src/app/my-gallery/create/page.jsx
- src/app/my-gallery/page.jsx
- src/app/sale/page.jsx
- src/components/market/MyCardsSellBottomSheet.jsx
- src/components/ui/card/cardOverview/CardImage.jsx
- src/components/ui/card/cardOverview/CardOverview.jsx
- src/lib/api/galleryApi.js
- src/lib/api/marketApi.js
- src/utils/countFilterValues.js
- 기능 구현
- 포토카드 클릭 시 판매/구매 상세 페이지로 이동 기능 추가
- 버그 수정
- 카드 클릭 시 id 대신 전체 card 객체를 전달하도록 수정
- 마켓플레이스 카드에서 뱃지(saleStatus) 노출되지 않도록 조건 수정
- 페이지네이션 take 수 수정
- 리팩토링
- React Hook Form을 사용하여 폼 리팩토링
- 공통 fetch 로직을 fetchClient.js 기반으로 통일
> 마켓플레이스, 마이갤러리, 포토카드 생성, 판매 포토카드 페이지 기능 개선 및 리팩토링

- src/app/purchase/[id]/page.jsx
- src/lib/api/purchase.js
- 판매자일 때 자동으로 판매 페이지로 리다이렉트 처리 완료
> fix: isSeller 플래그를 활용하여 구매자인지 판매자인지 구분

- src/app/market/page.jsx
- src/components/market/MyCardsSellBottomSheet.jsx
- src/lib/api/marketApi.js
- src/providers/RouteGuard.jsx
- 유저플로우에 맞춰 비회원도 마켓플레이스 접근이 가능하도록 수정
- 비회원이 카드를 클릭하거나 버튼을 눌렀을 때 로그인 모달이 뜨도록 구현
- 비회원일 때 판매 포토카드 조회요청이 안 가도록 판매 바텀시트 수정
- 무한스크롤링 시 같은 카드 불러오는 문제 해결
> feat: 비회원도 마켓 접근 가능하도록 수정 및 비회원 클릭 시 모달 표시

- src/app/my-gallery/create/page.jsx
- src/app/my-gallery/page.jsx
- src/app/sale/page.jsx
- 가격 인풋 제한 로직 추가
- 인풋 창 아래 에러 메세지로 표시
- 다른 변수명으로 인한 **페이지네이션 불러오기 오류** 수정
> feat: 가격 인풋 제한 로직 추가 및 페이지네이션 오류 해결

- src/components/layout/NotificationModal.jsx
- 알림 모달에서 클릭 시 판매 페이지로 이동하기 연결했습니다.
> fix: 알림 판매 페이지로 이동 연결

- README.md
- src/app/market/page.jsx
- src/app/my-gallery/page.jsx
- src/app/sale/page.jsx
- src/hooks/useLocalUser.js
- src/hooks/useMarketInfiniteCards.js
- src/lib/api/galleryApi.js
- src/lib/api/marketApi.js
- src/utils/filterOptions.js
> 마켓, 갤러리, 판매 페이지 리팩토링

- src/components/layout/Header.jsx
- src/components/layout/ProfileMobileModal.jsx
- 모바일 버전에서 모달창 클릭 시 닫히는 상황이 있어 수정
> fix: 모바일 버전 모달창 수정
